#ifndef __NRF24L01_H_
#define __NRF24L01_H_

void nrf_init();
void nrf_print_config();

// SPI Commands

#define NRF_COMMAND_R_REGISTER(addr)     0x00 + (addr & 0x1F)
#define NRF_COMMAND_W_REGISTER(addr)     0x20 + (addr & 0x1F)
#define NRF_COMMAND_R_RX_PAYLOAD         0x61
#define NRF_COMMAND_W_TX_PAYLOAD         0xA0
#define NRF_COMMAND_FLUSH_TX             0xF1
#define NRF_COMMAND_FLUSH_RX             0xF2
#define NRF_COMMAND_REUSE_TX_PL          0xF3
#define NRF_COMMAND_R_RX_PL_WID          0x60
#define NRF_COMMAND_W_ACK_PAYLOAD(pipe)  0xA8 + (pipe & 0x7)
#define NRF_COMMAND_W_TX_PAYLOAD_NO_ACK  0xB0
#define NRF_COMMAND_NOP                  0xFF


// Register map table

#define NRF_REGISTER_CONFIG 0x00
#define NRF_REGISTER_CONFIG_MASK_RX_DR  (1 << 6)
#define NRF_REGISTER_CONFIG_MASK_TX_DS  (1 << 5)
#define NRF_REGISTER_CONFIG_MASK_MAX_RT (1 << 4)
#define NRF_REGISTER_CONFIG_MASK_EN_CRC (1 << 3)
#define NRF_REGISTER_CONFIG_CRCO        (1 << 2)
#define NRF_REGISTER_CONFIG_PWR_UP      (1 << 1)
#define NRF_REGISTER_CONFIG_PRIM_RX     (1 << 0)

#define NRF_REGISTER_EN_AA 0x01
#define NRF_REGISTER_EN_AA_P5 (1 << 5)
#define NRF_REGISTER_EN_AA_P4 (1 << 4)
#define NRF_REGISTER_EN_AA_P3 (1 << 3)
#define NRF_REGISTER_EN_AA_P2 (1 << 2)
#define NRF_REGISTER_EN_AA_P1 (1 << 1)
#define NRF_REGISTER_EN_AA_P0 (1 << 0)

#define NRF_REGISTER_EN_RXADDR 0x02
#define NRF_REGISTER_EN_RXADDR_ENAA(pipe) (1 << pipe)
#define NRF_REGISTER_EN_RXADDR_ENAA_P5 (1 << 5)
#define NRF_REGISTER_EN_RXADDR_ENAA_P4 (1 << 4)
#define NRF_REGISTER_EN_RXADDR_ENAA_P3 (1 << 3)
#define NRF_REGISTER_EN_RXADDR_ENAA_P2 (1 << 2)
#define NRF_REGISTER_EN_RXADDR_ENAA_P1 (1 << 1)
#define NRF_REGISTER_EN_RXADDR_ENAA_P0 (1 << 0)

#define NRF_REGISTER_SETUP_RETR 0x04

#define NRF_REGISTER_RF_CH 0x05

#define NRF_REGISTER_RF_SETUP 0x06
#define NRF_REGISTER_RF_SETUP_CONT_WAVE  (1 << 7)
#define NRF_REGISTER_RF_SETUP_RF_DR_LOW  (1 << 5)
#define NRF_REGISTER_RF_SETUP_RF_DR_HIGH (1 << 3)
#define NRF_REGISTER_RF_SETUP_RF_PWR     (1 << 2) | (1 << 1)
#define NRF_REGISTER_RF_SETUP_RF_PWR_18DBM 00
#define NRF_REGISTER_RF_SETUP_RF_PWR_12DBM 01
#define NRF_REGISTER_RF_SETUP_RF_PWR_6DBM  10
#define NRF_REGISTER_RF_SETUP_RF_PWR_0DBM  11

#define NRF_REGISTER_STATUS 0x07
#define NRF_REGISTER_STATUS_RX_DR   (1 << 6)
#define NRF_REGISTER_STATUS_TX_DS   (1 << 5)
#define NRF_REGISTER_STATUS_MAX_RT  (1 << 4)
#define NRF_REGISTER_STATUS_RX_P_NO 0xE
#define NRF_REGISTER_STATUS_TX_FULL (1 << 0)

#define NRF_REGISTER_OBSERVE_TX 0x08

#define NRF_REGISTER_RPD 0x09
#define NRF_REGISTER_RPD_RPD (1 << 0)

#define NRF_REGISTER_RX_ADDR(pipe) NRF_REGISTER_RX_ADDR_P0 + (pipe & 0x7)
#define NRF_REGISTER_RX_ADDR_P0 0x0A
#define NRF_REGISTER_RX_ADDR_P1 0x0B
#define NRF_REGISTER_RX_ADDR_P2 0x0C
#define NRF_REGISTER_RX_ADDR_P3 0x0D
#define NRF_REGISTER_RX_ADDR_P4 0x0E
#define NRF_REGISTER_RX_ADDR_P5 0x0F

#define NRF_REGISTER_TX_ADDR     0x10

#define NRF_REGISTER_RX_PW(pipe) NRF_REGISTER_RX_PW_P0 + (pipe & 0x7)
#define NRF_REGISTER_RX_PW_P0 0x11
#define NRF_REGISTER_RX_PW_P1 0x12
#define NRF_REGISTER_RX_PW_P2 0x13
#define NRF_REGISTER_RX_PW_P3 0x14
#define NRF_REGISTER_RX_PW_P4 0x15
#define NRF_REGISTER_RX_PW_P5 0x16

#define NRF_REGISTER_FIFO_STATUS 0x17
#define NRF_REGISTER_FIFO_STATUS_TX_REUSE (1 << 6)
#define NRF_REGISTER_FIFO_STATUS_TX_FULL  (1 << 5)
#define NRF_REGISTER_FIFO_STATUS_TX_EMPTY (1 << 4)
#define NRF_REGISTER_FIFO_STATUS_RX_FULL  (1 << 1)
#define NRF_REGISTER_FIFO_STATUS_RX_EMPTY (1 << 0)

#define NRF_REGISTER_DYNPD 0x1C
#define NRF_REGISTER_DYNPD_DPL(pipe) (1 << pipe)
#define NRF_REGISTER_DYNPD_DPL_P5 (1 << 5)
#define NRF_REGISTER_DYNPD_DPL_P4 (1 << 4)
#define NRF_REGISTER_DYNPD_DPL_P3 (1 << 3)
#define NRF_REGISTER_DYNPD_DPL_P2 (1 << 2)
#define NRF_REGISTER_DYNPD_DPL_P1 (1 << 1)
#define NRF_REGISTER_DYNPD_DPL_P0 (1 << 0)

#define NRF_REGISTER_FEATURE 0x1D
#define NRF_REGISTER_FEATURE_EN_DPL     (1 << 2)
#define NRF_REGISTER_FEATURE_ACK_PAY    (1 << 1)
#define NRF_REGISTER_FEATURE_EN_DYN_ACK (1 << 0)

#endif
